"""
Django settings for biomio_backend_SCIM project.

Generated by 'django-admin startproject' using Django 1.10.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import redis

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%m-2p_lo5bae90x48m%o&=jm2#o60a4)u0f#n0_(huovuouzqw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'biomio_backend_SCIM.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'biomio_backend_SCIM.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    # mysql_host = '35.161.49.206'
    # mysql_user = 'biomio_gate'
    # mysql_pass = 'gate'
    # mysql_db_name = 'biomio_db'

    'default': {
        'ENGINE': 'django.db.backends.mysql',
        # 'ENGINE': 'django.db.backends.postgresql_psycopg2',
        # 'NAME': 'biomio_db',
        'NAME': os.environ.get('BIOMIO_DB_NAME'),
        'USER': os.environ.get('BIOMIO_DB_USER'),
        # 'USER': 'biomio_gate',
        'PASSWORD': os.environ.get('BIOMIO_DB_PASS'),
        'HOST': os.environ.get('BIOMIO_DB_HOST'),
        # 'HOST': '35.161.49.206',
        'PORT': os.environ.get('BIOMIO_DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'


SCIM_ADDR = 'urn:ietf:params:scim:schemas:core:2.0:%s'

# AI_REST_URL = 'http://gate.biom.io/training?device_id=%s&code=AAAAA'
AI_REST_URL = os.environ.get('AI_REST_URL')

REDIS_HOST = os.environ.get('BIOMIO_REDIS_HOST')
REDIS_PORT = os.environ.get('BIOMIO_REDIS_PORT')

pool = redis.ConnectionPool(host=REDIS_HOST, port=REDIS_PORT, db=0)
redis_conn = redis.Redis(connection_pool=pool)

REDIS_BIOMIO_GENERAL_CHANNEL = 'biomio_general:%s'
REDIS_TRAINING_STATUS_KEY_PARAMS = REDIS_BIOMIO_GENERAL_CHANNEL % 'params:training:status:%s'